CREATE SCHEMA IF NOT EXISTS SEMANTIC_MODEL;

CREATE TABLE SEMANTIC_MODEL.ASSERTION (
    PACKAGE_ID VARCHAR NOT NULL CHECK (PACKAGE_ID = UPPER(PACKAGE_ID)),
    ORDINAL INTEGER NOT NULL CHECK (ORDINAL > 0),
    SUBJECT VARCHAR NOT NULL CHECK (SUBJECT = UPPER(SUBJECT)),
    RELATION VARCHAR NOT NULL CHECK (RELATION = UPPER(RELATION)),
    OBJECT VARCHAR NOT NULL CHECK (OBJECT = UPPER(OBJECT)),
    PRIMARY KEY (PACKAGE_ID, ORDINAL),
    UNIQUE (PACKAGE_ID, SUBJECT, RELATION, OBJECT)
);

CREATE TABLE SEMANTIC_MODEL.RELATION_SCHEMA (
    RELATION VARCHAR PRIMARY KEY CHECK (RELATION = UPPER(RELATION)),
    SUBJECT_KINDS VARCHAR NOT NULL CHECK (SUBJECT_KINDS = UPPER(SUBJECT_KINDS)),
    OBJECT_ROLE VARCHAR NOT NULL CHECK (OBJECT_ROLE = UPPER(OBJECT_ROLE)),
    OBJECT_CONSTRAINT VARCHAR NOT NULL CHECK (OBJECT_CONSTRAINT = UPPER(OBJECT_CONSTRAINT)),
    MIN_CARDINALITY INTEGER NOT NULL CHECK (MIN_CARDINALITY >= 0),
    MAX_CARDINALITY INTEGER NULL CHECK (
        MAX_CARDINALITY IS NULL OR MAX_CARDINALITY >= MIN_CARDINALITY
    )
);
